language: python
dist: xenial
sudo: required
cache: pip
python: 3.5
env:
  - TOX_ENV=py27-dj17-sqlite
  - TOX_ENV=py27-dj17-postgres
  - TOX_ENV=py27-dj18-sqlite
  - TOX_ENV=py27-dj18-postgres
  - TOX_ENV=py27-dj19-sqlite
  - TOX_ENV=py27-dj19-postgres
  - TOX_ENV=py27-dj110-sqlite
  - TOX_ENV=py27-dj110-postgres
  - TOX_ENV=py27-dj111-sqlite
  - TOX_ENV=py27-dj111-postgres
  - TOX_ENV=py34-dj17-sqlite
  - TOX_ENV=py34-dj17-postgres
  - TOX_ENV=py34-dj18-sqlite
  - TOX_ENV=py34-dj18-postgres
  - TOX_ENV=py34-dj19-sqlite
  - TOX_ENV=py34-dj19-postgres
  - TOX_ENV=py34-dj110-sqlite
  - TOX_ENV=py34-dj110-postgres
  - TOX_ENV=py34-dj111-sqlite
  - TOX_ENV=py34-dj111-postgres
  - TOX_ENV=py34-dj20-sqlite
  - TOX_ENV=py34-dj20-postgres
  - TOX_ENV=py35-dj18-sqlite
  - TOX_ENV=py35-dj18-postgres
  - TOX_ENV=py35-dj19-sqlite
  - TOX_ENV=py35-dj19-postgres
  - TOX_ENV=py35-dj110-sqlite
  - TOX_ENV=py35-dj110-postgres
  - TOX_ENV=py35-dj111-sqlite
  - TOX_ENV=py35-dj111-postgres
  - TOX_ENV=py35-dj20-sqlite
  - TOX_ENV=py35-dj20-postgres
  - TOX_ENV=py35-dj21-sqlite
  - TOX_ENV=py35-dj21-postgres
  - TOX_ENV=py35-dj22-sqlite
  - TOX_ENV=py35-dj22-postgres
  - TOX_ENV=py36-dj111-sqlite
  - TOX_ENV=py36-dj111-postgres
  - TOX_ENV=py36-dj20-sqlite
  - TOX_ENV=py36-dj20-postgres
  - TOX_ENV=py36-dj21-sqlite
  - TOX_ENV=py36-dj21-postgres
  - TOX_ENV=py36-dj22-sqlite
  - TOX_ENV=py36-dj22-postgres
  - TOX_ENV=py36-djmaster-sqlite
  - TOX_ENV=py36-djmaster-postgres
  - TOX_ENV=py37-dj111-sqlite
  - TOX_ENV=py37-dj111-postgres
  - TOX_ENV=py37-dj20-sqlite
  - TOX_ENV=py37-dj20-postgres
  - TOX_ENV=py37-dj21-sqlite
  - TOX_ENV=py37-dj21-postgres
  - TOX_ENV=py37-dj22-sqlite
  - TOX_ENV=py37-dj22-postgres
  - TOX_ENV=py37-djmaster-sqlite
  - TOX_ENV=py37-djmaster-postgres
matrix:
  allow_failures:
    - env:
      - TOX_ENV=py36-djmaster-sqlite
      - TOX_ENV=py36-djmaster-postgres
    - env:
      - TOX_ENV=py37-djmaster-sqlite
      - TOX_ENV=py37-djmaster-postgres
install:
  - pip install tox
services:
  - postgresql
before_script:
  - psql -c 'create database admin_interface;' -U postgres
script:
  - tox -e $TOX_ENV
