language: python
python: 3.5
env:
  - TOX_ENV=py27-17
  - TOX_ENV=py27-18
  - TOX_ENV=py27-19
  - TOX_ENV=py27-110
  - TOX_ENV=py27-111
  - TOX_ENV=py34-17
  - TOX_ENV=py34-18
  - TOX_ENV=py34-19
  - TOX_ENV=py34-110
  - TOX_ENV=py34-111
  - TOX_ENV=py34-20
  - TOX_ENV=py34-21
  - TOX_ENV=py35-18
  - TOX_ENV=py35-19
  - TOX_ENV=py35-110
  - TOX_ENV=py35-111
  - TOX_ENV=py35-20
  - TOX_ENV=py35-21
  - TOX_ENV=py35-master
matrix:
  include:
    - python: "3.6"
      env: TOX_ENV=py36-111
    - python: "3.6"
      env: TOX_ENV=py36-20
    - python: "3.6"
      env: TOX_ENV=py36-21
    - python: "3.6"
      env: TOX_ENV=py36-master
  allow_failures:
    - env: TOX_ENV=py35-master
    - env: TOX_ENV=py36-master
install:
  - pip install tox
script:
  - tox -e $TOX_ENV
sudo: false
